package view;

import dao.LoginDAO;
import dao.UpdateAccountDAO;
import java.awt.Font;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Account;

public class ChangePassWindow extends javax.swing.JFrame {

    public ChangePassWindow() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/login.png")));
        addPlaceHolderStyle(tfUser);
        addPlaceHolderStyle(tfPass);
        addPlaceHolderStyle(tfNewPass);
        addPlaceHolderStyle(tfConfirmPass);
    }

    private void addPlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }

    private void removePlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChangePassPanel = new javax.swing.JPanel();
        changePassLabel = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JLabel();
        txtConfirmPass = new javax.swing.JLabel();
        changeBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        tfConfirmPass = new javax.swing.JPasswordField();
        tfPass = new javax.swing.JPasswordField();
        tfNewPass = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChangePassPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ChangePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        changePassLabel.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        changePassLabel.setForeground(new java.awt.Color(51, 51, 0));
        changePassLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-password.png"))); // NOI18N
        changePassLabel.setText("CHANGE PASSWORD");
        getContentPane().add(changePassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        txtUser.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        txtUser.setText("Username");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 20));

        tfUser.setText("Username");
        tfUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUserFocusLost(evt);
            }
        });
        getContentPane().add(tfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 180, -1));

        txtPass.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        txtPass.setText("Password");
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 20));

        txtNewPass.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        txtNewPass.setText("New Password");
        getContentPane().add(txtNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 20));

        txtConfirmPass.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        txtConfirmPass.setText("Confirm Password");
        getContentPane().add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 20));

        changeBtn.setBackground(new java.awt.Color(0, 153, 255));
        changeBtn.setForeground(new java.awt.Color(51, 0, 0));
        changeBtn.setText("Change");
        changeBtn.setBorderPainted(false);
        changeBtn.setFocusable(false);
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(changeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        cancelBtn.setBackground(new java.awt.Color(0, 153, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorderPainted(false);
        cancelBtn.setFocusable(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        tfConfirmPass.setText("Confirm Password");
        tfConfirmPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfConfirmPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfConfirmPassFocusLost(evt);
            }
        });
        getContentPane().add(tfConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 180, -1));

        tfPass.setText("Password");
        tfPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPassFocusLost(evt);
            }
        });
        getContentPane().add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 180, -1));

        tfNewPass.setText("New Password");
        tfNewPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNewPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNewPassFocusLost(evt);
            }
        });
        getContentPane().add(tfNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 180, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/colorfulBackground.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserFocusGained
        if (tfUser.getText().equals("Username")) {
            tfUser.setText(null);
            tfUser.requestFocus();
            removePlaceHolderStyle(tfUser);
        }
    }//GEN-LAST:event_tfUserFocusGained

    private void tfUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserFocusLost
        if (tfUser.getText().length() == 0) {
            addPlaceHolderStyle(tfUser);
            tfUser.setText("Username");
        }
    }//GEN-LAST:event_tfUserFocusLost

    private void tfPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPassFocusGained
        if (String.valueOf(tfPass.getPassword()).equals("Password")) {
            tfPass.setText(null);
            tfPass.requestFocus();
            tfPass.setEchoChar('*');
            removePlaceHolderStyle(tfPass);
        }
    }//GEN-LAST:event_tfPassFocusGained

    private void tfPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPassFocusLost
        if (String.valueOf(tfPass.getPassword()).length() == 0) {
            addPlaceHolderStyle(tfPass);
            tfPass.setText("Password");
            tfPass.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_tfPassFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void tfConfirmPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfConfirmPassFocusLost
        if (String.valueOf(tfConfirmPass.getPassword()).length() == 0) {
            addPlaceHolderStyle(tfConfirmPass);
            tfConfirmPass.setText("Confirm Password");
            tfConfirmPass.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_tfConfirmPassFocusLost

    private void tfConfirmPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfConfirmPassFocusGained
        if (String.valueOf(tfConfirmPass.getPassword()).equals("Confirm Password")) {
            tfConfirmPass.setText(null);
            tfConfirmPass.requestFocus();
            tfConfirmPass.setEchoChar('*');
            removePlaceHolderStyle(tfConfirmPass);
        }
    }//GEN-LAST:event_tfConfirmPassFocusGained

    private void tfNewPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNewPassFocusLost
        if (String.valueOf(tfNewPass.getPassword()).length() == 0) {
            addPlaceHolderStyle(tfNewPass);
            tfNewPass.setText("New Password");
            tfNewPass.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_tfNewPassFocusLost

    private void tfNewPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNewPassFocusGained
        if (String.valueOf(tfNewPass.getPassword()).equals("New Password")) {
            tfNewPass.setText(null);
            tfNewPass.requestFocus();
            tfNewPass.setEchoChar('*');
            removePlaceHolderStyle(tfNewPass);
        }
    }//GEN-LAST:event_tfNewPassFocusGained

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        String username = tfUser.getText();
        String password = String.valueOf(tfPass.getPassword());
        String newPass = String.valueOf(tfNewPass.getPassword());
        String confirmPass = String.valueOf(tfConfirmPass.getPassword());
        if (username.equals("Username") || password.equals("Password")
                || newPass.equals("New Password") || confirmPass.equals("Confirm Password")) {
            JOptionPane.showMessageDialog(null, "Information cannot be left blank");
            return;
        }
        try {
            if (newPass.equals(confirmPass) && newPass.length() > 4) {
                LoginDAO ld = new LoginDAO();
                Account a = (Account) ld.checkLogin(username, password);
                if (a != null) {
                    UpdateAccountDAO ud = new UpdateAccountDAO();
                    ud.updateAccount(username, newPass);
                    JOptionPane.showMessageDialog(null, "Change password successfully");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Username or password is incorrect");
                }

            } else {
                JOptionPane.showMessageDialog(null, "New password and confirm password do not match (Password length > 4)");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_changeBtnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ChangePassWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChangePassPanel;
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton changeBtn;
    private javax.swing.JLabel changePassLabel;
    private javax.swing.JPasswordField tfConfirmPass;
    private javax.swing.JPasswordField tfNewPass;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfUser;
    private javax.swing.JLabel txtConfirmPass;
    private javax.swing.JLabel txtNewPass;
    private javax.swing.JLabel txtPass;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
